/**
 * Conan Doyle — AlfasaAutoSEO Media System
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Purpose: Give AlfasaAutoSEO and article writers instant access to creator
 * media (YouTube thumbnails, Instagram embeds) when writing or publishing
 * creator-related articles on ObjectWire.
 *
 * ─── COMPONENTS ──────────────────────────────────────────────────────────────
 *
 *   CreatorMediaKit      — ONE component to rule them all. YouTube grid +
 *                          Instagram gallery in a single drop-in block.
 *                          Start here for new articles.
 *
 *   YouTubeThumbnailGrid — YouTube video thumbnail grid. Reads from
 *                          public/youtube-data/[slug].json. No API key at render.
 *
 *   InstagramEmbed       — Single official Instagram post embed.
 *   InstagramGallery     — Grid of Instagram post embeds.
 *
 * ─── SCRIPTS (run in terminal) ───────────────────────────────────────────────
 *
 *   fetch-creator-media.ts  — PRIMARY. Fetch YouTube + generate both HTML
 *                             (for Supabase content_html) and JSX (for page.tsx).
 *                             Use this before writing any creator article.
 *
 *   fetch-youtube-channel.ts — Low-level. Fetch only YouTube channel data.
 *
 * ─── QUICK START (AlfasaAutoSEO WORKFLOW) ────────────────────────────────────
 *
 *   Step 1 — Get a free YouTube API key (one time):
 *     console.cloud.google.com → Create Project → Enable "YouTube Data API v3"
 *     → Credentials → Create API Key
 *     Add to .env.local:  YOUTUBE_API_KEY=your_key_here
 *
 *   Step 2 — Before writing a creator article, run:
 *     npx tsx components/conan_doyle/fetch-creator-media.ts \
 *       --slug=kai-cenat \
 *       --youtube=@KaiCenat \
 *       --instagram=kacenat
 *
 *     This prints TWO ready-to-paste snippets:
 *       • HTML block  → paste into Supabase content_html
 *       • JSX block   → paste into page.tsx
 *     And saves: public/youtube-data/kai-cenat.json
 *
 *   Step 3 — In a page.tsx article (content-in-code):
 *     import { CreatorMediaKit } from '@/components/conan_doyle';
 *
 *     <CreatorMediaKit
 *       youtubeSlug="kai-cenat"
 *       instagramPosts={[
 *         'https://www.instagram.com/p/SHORTCODE1/',
 *         'https://www.instagram.com/p/SHORTCODE2/',
 *         'https://www.instagram.com/p/SHORTCODE3/',
 *       ]}
 *       instagramHandle="kacenat"
 *       heading="Kai Cenat"
 *     />
 *
 *   Step 3 (alternative) — In a Supabase content_html article:
 *     Copy the HTML output from Step 2 directly into the content_html field.
 *     YouTube thumbnails use <img> tags (no JS needed).
 *     Instagram embeds use the official blockquote embed format.
 *
 * ─── INSTAGRAM SHORTCODES ────────────────────────────────────────────────────
 *
 *   Visit https://www.instagram.com/[username]/
 *   Click any post → the URL is https://www.instagram.com/p/SHORTCODE/
 *   The SHORTCODE is the string after /p/ — e.g. 'C7xXyz12345'
 *
 * ─── FILE LOCATIONS ──────────────────────────────────────────────────────────
 *
 *   Components:  components/conan_doyle/
 *   Data files:  public/youtube-data/[slug].json  (auto-generated by scripts)
 */

// ─── Components ───────────────────────────────────────────────────────────────

export { CreatorMediaKit } from './CreatorMediaKit';
export type { CreatorMediaKitProps } from './CreatorMediaKit';

export { InstagramEmbed, InstagramGallery } from './InstagramEmbed';
export type { InstagramEmbedProps, InstagramGalleryProps, InstagramGalleryPost } from './InstagramEmbed';

export { YouTubeThumbnailGrid } from './YouTubeThumbnailGrid';
export type { YouTubeThumbnailGridProps, YTVideoItem, ThumbnailQuality } from './YouTubeThumbnailGrid';
