export const SITE_CONFIG = {
  name: "Objective Wire",
  shortName: "oWire",
  url: "https://www.objectwire.org",
  description: "Objective Wire is a licensed investigative media agency and 501(c)(3) nonprofit based in Austin, Texas. We take on investigative reporting cases, PI work, and accountability journalism. Investigate. Document. Publish.",
  tagline: "Investigate. Document. Publish.",
  locale: "en_US",
  author: "Objective Wire Editorial",
  email: "editorial@objectwire.org",
  phone: "(575) 495-0323",
  address: "2921 E 17th St Building 3, APT 3205, Austin, TX 78702",
  twitter: "@objectwire",
  // /opengraph-image is auto-generated by app/opengraph-image.tsx (1200x630 brand card).
  socialImage: "https://www.objectwire.org/opengraph-image",
  defaultOgImage: "https://www.objectwire.org/opengraph-image",
};

export const BLOCKED_USER_AGENTS = [
  'CCBot',
];

export const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'fbclid',
  'gclid',
];

export const DUPLICATE_PARAMS = [
  'ref',
  'source',
  'campaign',
];
