// Branch-aware canonical domain.
// Set NEXT_PUBLIC_SITE_URL in Railway per-service env vars:
//   main service  -> https://www.objectivewire.com
//   org service   -> https://www.objectivewire.org
// Falls back to .org locally so org-branch dev works with no env var.
const _siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.objectivewire.org';

export const SITE_CONFIG = {
  name: "Objective Wire",
  shortName: "oWire",
  url: _siteUrl,
  description: "Objective Wire is a 501(c)(3) nonprofit investigative agency and public-interest magazine filed in Wyoming and operating throughout Texas. Private investigative services, documented field work, and public-interest reporting — all in one organization.",
  tagline: "Texas Investigations. Documented & Published.",
  locale: "en_US",
  author: "Objective Wire Editorial",
  email: "editorial@objectivewire.org",
  phone: "(575) 495-0323",
  address: "2921 E 17th St Building 3, APT 3205, Austin, TX 78702",
  twitter: "@owire",
  // /opengraph-image is auto-generated by app/opengraph-image.tsx (1200x630 brand card).
  socialImage: `${_siteUrl}/opengraph-image`,
  defaultOgImage: `${_siteUrl}/opengraph-image`,
};

export const BLOCKED_USER_AGENTS = [
  'CCBot',
];

export const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'fbclid',
  'gclid',
];

export const DUPLICATE_PARAMS = [
  'ref',
  'source',
  'campaign',
];
