export const SITE_CONFIG = {
  name: "Objective Wire",
  shortName: "oWire",
  url: "https://www.objectivewire.org",
  description: "Objective Wire is a licensed investigative newsroom and 501(c)(3) nonprofit based in Austin, Texas. Our reporters hold Texas PI credentials, applied to original investigative reporting on public records, accountability, cars, creators, and culture.",
  tagline: "Licensed. Investigated. Published.",
  locale: "en_US",
  author: "Objective Wire Editorial",
  email: "editorial@objectivewire.org",
  phone: "(575) 495-0323",
  address: "2921 E 17th St Building 3, APT 3205, Austin, TX 78702",
  twitter: "@owire",
  // /opengraph-image is auto-generated by app/opengraph-image.tsx (1200x630 brand card).
  socialImage: "https://www.objectivewire.org/opengraph-image",
  defaultOgImage: "https://www.objectivewire.org/opengraph-image",
};

export const BLOCKED_USER_AGENTS = [
  'CCBot',
];

export const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'fbclid',
  'gclid',
];

export const DUPLICATE_PARAMS = [
  'ref',
  'source',
  'campaign',
];
